name: Deploy English version to Firebase
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Clean
        run: |
          rm -rf ./dist/*
          rm -rf ./reports/*
          rm -rf ./coverage/*
          mkdir -p ./reports
      - name: Build Angular
        run: |
          npm install
          npm run build-en-regular-prod -- --base-href 'https://sciddle-riddle-eng.web.app/'
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project sciddle-riddle --only hosting:sciddle-riddle-eng
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
